# Generated by Django 5.2.16 on 2026-07-20 02:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_friendlier_field_labels'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['name'], 'verbose_name': 'autor', 'verbose_name_plural': 'autores'},
        ),
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['-created_at'], 'verbose_name': 'livro', 'verbose_name_plural': 'livros'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'categoria', 'verbose_name_plural': 'categorias'},
        ),
        migrations.AlterModelOptions(
            name='readinglistitem',
            options={'ordering': ['-created_at'], 'verbose_name': 'livro salvo', 'verbose_name_plural': 'livros salvos pelos leitores'},
        ),
        migrations.AlterField(
            model_name='author',
            name='bio',
            field=models.TextField(blank=True, help_text='Texto curto sobre o autor, se quiser.', verbose_name='biografia (opcional)'),
        ),
        migrations.AlterField(
            model_name='author',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='criado em'),
        ),
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(max_length=200, verbose_name='nome'),
        ),
        migrations.AlterField(
            model_name='author',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='authors',
            field=models.ManyToManyField(blank=True, help_text='Escolha um ou mais autores na lista ao lado.', related_name='books', to='catalog.author', verbose_name='autores'),
        ),
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='books', to='catalog.category', verbose_name='categoria'),
        ),
        migrations.AlterField(
            model_name='book',
            name='cover_url',
            field=models.URLField(blank=True, help_text='Cole o link completo da imagem (começa com https://).', verbose_name='link da capa (opcional)'),
        ),
        migrations.AlterField(
            model_name='book',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='criado em'),
        ),
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.TextField(help_text='Resumo do livro para o visitante. Escreva de forma simples.', verbose_name='descrição'),
        ),
        migrations.AlterField(
            model_name='book',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Marque para o livro aparecer em destaque na home do site.', verbose_name='destaque na página inicial'),
        ),
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(blank=True, max_length=20, verbose_name='ISBN (opcional)'),
        ),
        migrations.AlterField(
            model_name='book',
            name='published_date',
            field=models.DateField(blank=True, help_text='Se souber, use o formato AAAA-MM-DD (ex.: 2024-05-10).', null=True, verbose_name='data de publicação (opcional)'),
        ),
        migrations.AlterField(
            model_name='book',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='subtitle',
            field=models.CharField(blank=True, max_length=255, verbose_name='subtítulo (opcional)'),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=255, verbose_name='título'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, verbose_name='nome'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='readinglistitem',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='on_shelves', to='catalog.book', verbose_name='livro'),
        ),
        migrations.AlterField(
            model_name='readinglistitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='salvo em'),
        ),
        migrations.AlterField(
            model_name='readinglistitem',
            name='notes',
            field=models.CharField(blank=True, max_length=255, verbose_name='observação (opcional)'),
        ),
        migrations.AlterField(
            model_name='readinglistitem',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_list', to=settings.AUTH_USER_MODEL, verbose_name='leitor'),
        ),
    ]
